[package]
name = "ppm-cli"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
anyhow = "1.0.97"
env_logger = "0.11.8"
thiserror = "2.0.12"
clap = { version = "4.5.35", features = ["derive"] }
