name: PPM-CLI PR Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  check_licenses:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Change script to executable just in case
        run: chmod +x license_checker.sh
      - name: Run license script
        run: ./license_checker.sh

  check_formatting:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - run: cargo fmt --all -- --check

  check_build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - run: cargo build --release --verbose

  test_build:
    runs-on: ubuntu-latest
    needs: check_build
    steps:
      - run: cargo test --verbose

  check_with_linter:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - run: cargo clippy -- -Dwarnings
