name: PPM-CLI PR Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check License in Rust files
        run: |
          chmod +x license_checker.sh
          ./license_checker.sh
        shell: bash
      - name: Check Formatting
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo test --verbose
      - name: Linter
        run: cargo clippy -- -Dwarnings
