name: PPM-CLI PR Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Enter Project
        run: cd ppm-cli
      - name: Check Formatting
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo test --verbose
      - name: Linter
        run: cargo clippy -- -Dwarnings
